# My Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]],np.int8)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1] =40

In [7]:
myarr

array([[ 3, 40, 37,  7]], dtype=int8)

## Array Creration: Conversion from other python structure ##

In [13]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [14]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [15]:
listarray.dtype

dtype('int32')

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
np.array({34,23},dtype=object)

array({34, 23}, dtype=object)

In [22]:
zeros = np.zeros((2,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
zeros.shape

(2, 5)

In [28]:
rng=np.arange(15)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
lspace=np.linspace(1,5,4)

In [38]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [39]:
emp=np.empty((4,6))

In [40]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.42419530e-306, 7.56597770e-307, 7.56587585e-307],
       [7.56593017e-307, 1.24610383e-306, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306, 2.22522597e-306],
       [1.33511969e-306, 1.78022342e-306, 1.05700345e-307,
        1.00132653e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 2.31420176e-306,
        9.34593493e-307, 1.60220393e-306, 2.56765117e-312]])

In [41]:
emp_like =np.empty_like(lspace)

In [42]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [43]:
ide=np.identity(45)

In [44]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [45]:
ide.shape

(45, 45)

In [46]:
arr=np.arange(99)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [51]:
arr=arr.reshape(3,33)

In [52]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [55]:
arr.shape

(3, 33)

In [56]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [57]:
ar=np.array(x)

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.sum(axis=0)

array([12,  8,  9])

In [61]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [63]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [64]:
ar.flat

In [65]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [67]:
ar.ndim

2

In [68]:
ar.size

9

In [69]:
ar.nbytes

36

In [70]:
one =np.array([1,2,4,634,2])

In [71]:
one.argmax()

3

In [72]:
one.argmin()

0

In [73]:
one.argsort()

array([0, 1, 4, 2, 3], dtype=int32)

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [77]:
ar.argmin()

8

In [78]:
ar.argmax()

6

In [80]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [81]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [84]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

In [86]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [89]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [90]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [91]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [92]:
ar.sum()

29

In [93]:
ar.max()

7

In [94]:
ar.min()

0

In [95]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [99]:
np.where(ar>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [102]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

In [103]:
ar[1,2] = 0

In [104]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int32))

In [105]:
import sys

In [108]:
py_ar = [0,4,45,2]

In [109]:
np_ar = np.array(py_ar)

In [110]:
sys.getsizeof(1)*len(py_ar)

56

In [112]:
np_ar.itemsize * np_ar.size

16

In [113]:
np_ar.tolist()

[0, 4, 45, 2]